"""Extract unchanged ASCII glyphs from the pinned LVGL Montserrat bitmaps."""
from pathlib import Path
import re
import hashlib
import json

here = Path(__file__).resolve().parent
repo = here.parents[4]
source = repo / 'firmware/upstream/tangara-fw/lib/lvgl/src/font'
out = ['/* Generated by ui_assets/generate.py; see LICENSE-Montserrat.txt and LICENSE-LVGL.txt. */',
       '#pragma once', '#include <stdint.h>',
       'typedef struct { uint32_t offset; uint16_t advance; uint8_t w,h; int8_t x,y; } ui_glyph_t;',
       'typedef struct { const uint8_t *bitmap; const ui_glyph_t *glyphs; int height,baseline; } ui_font_t;']
hashes = {}
for size in (12, 16, 20, 26):
    path = source / ('lv_font_montserrat_%d.c' % size)
    text = path.read_text()
    hashes[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
    bitmap = text.split('glyph_bitmap[] = {', 1)[1].split('};', 1)[0]
    bitmap = re.sub(r'/\*.*?\*/', '', bitmap, flags=re.S)
    values = [int(v, 16) for v in re.findall(r'0x[0-9a-fA-F]+', bitmap)]
    desc = text.split('glyph_dsc[] = {', 1)[1].split('};', 1)[0]
    glyphs = [tuple(map(int, m)) for m in re.findall(
        r'\.bitmap_index = (\d+), \.adv_w = (\d+), \.box_w = (\d+), \.box_h = (\d+), \.ofs_x = (-?\d+), \.ofs_y = (-?\d+)', desc)][1:96]
    assert len(glyphs) == 95 and '.bitmap_format = 0' in text and '.bpp = 4' in text
    end = max(g[0] + (g[2]*g[3]+1)//2 for g in glyphs)
    out += ['static const uint8_t ui_bitmap_%d[] = {' % size]
    out += [','.join('0x%02x' % n for n in values[i:min(i+24,end)])+',' for i in range(0,end,24)]
    out += ['};','static const ui_glyph_t ui_glyphs_%d[] = {' % size]
    out += ['{%s},' % ','.join(map(str,g)) for g in glyphs]
    height = int(re.search(r'\.line_height = (\d+)', text)[1])
    baseline = int(re.search(r'\.base_line = (\d+)', text)[1])
    out += ['};', 'static const ui_font_t ui_font_%d = {ui_bitmap_%d,ui_glyphs_%d,%d,%d};' % (size,size,size,height,baseline)]
(here/'fonts.h').write_text('\n'.join(out)+'\n')
(here/'sources.json').write_text(json.dumps(hashes,indent=2)+'\n')
