/* Prepared trial library durations, 2026-09-26; exact relative path matches only. */
static unsigned trial_duration(const char *path) {
    if (!strcmp(path, "Creed/Human Clay/01-01 Are You Ready.mp3")) return 285;
    if (!strcmp(path, "Creed/Human Clay/01-02 What If.mp3")) return 318;
    if (!strcmp(path, "Creed/Human Clay/01-03 Beautiful.mp3")) return 260;
    if (!strcmp(path, "Creed/Human Clay/01-04 Say I.mp3")) return 316;
    if (!strcmp(path, "Creed/Human Clay/01-05 Wrong Way.mp3")) return 259;
    if (!strcmp(path, "Creed/Human Clay/01-07 Never Die.mp3")) return 291;
    if (!strcmp(path, "Creed/Human Clay/01-08 With Arms Wide Open.mp3")) return 275;
    if (!strcmp(path, "Creed/Human Clay/01-09 Higher.mp3")) return 317;
    if (!strcmp(path, "Creed/Human Clay/01-10 Wash Away Those Years.mp3")) return 364;
    if (!strcmp(path, "Creed/Human Clay/01-11 Inside Us All.mp3")) return 349;
    if (!strcmp(path, "Creed/Human Clay/01-12 Young Grow Old.mp3")) return 287;
    if (!strcmp(path, "Radiohead/In Rainbows/01 15 Step.mp3")) return 238;
    if (!strcmp(path, "Radiohead/In Rainbows/02 Bodysnatchers.mp3")) return 242;
    if (!strcmp(path, "Radiohead/In Rainbows/03 Nude.mp3")) return 256;
    if (!strcmp(path, "Radiohead/In Rainbows/04 Weird Fishes - Arpeggi.mp3")) return 318;
    if (!strcmp(path, "Radiohead/In Rainbows/05 All I Need.mp3")) return 229;
    if (!strcmp(path, "Radiohead/In Rainbows/06 Faust Arp.mp3")) return 130;
    if (!strcmp(path, "Radiohead/In Rainbows/07 Reckoner.mp3")) return 290;
    if (!strcmp(path, "Radiohead/In Rainbows/08 House Of Cards.mp3")) return 328;
    if (!strcmp(path, "Radiohead/In Rainbows/09 Jigsaw Falling Into Place.mp3")) return 249;
    if (!strcmp(path, "Radiohead/In Rainbows/10 Videotape.mp3")) return 280;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/01 Cats and Dogs.mp3")) return 116;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/02 Coeur d'Alene.mp3")) return 261;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/03 Ghosts.mp3")) return 259;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/04 Down in the Valley.mp3")) return 304;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/05 Rivers and Roads.mp3")) return 284;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/06 Honey Come Home.mp3")) return 201;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/07 Lost in My Mind.mp3")) return 259;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/08 Winter Song.mp3")) return 164;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/09 Sounds Like Hallelujah.mp3")) return 190;
    if (!strcmp(path, "The Head and The Heart/The Head and the Heart/10 Heaven Go Easy on Me.mp3")) return 340;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-01 Losing A Whole Year.mp3")) return 201;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-02 Narcolepsy.mp3")) return 229;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-03 Semi-Charmed Life.mp3")) return 269;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-04 Jumper.mp3")) return 273;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-05 Graduate.mp3")) return 190;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-06 How's It Going To Be.mp3")) return 254;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-07 Thanks A Lot.mp3")) return 298;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-08 Burning Man.mp3")) return 180;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-09 Good For You.mp3")) return 232;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-10 London.mp3")) return 187;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-11 I Want You.mp3")) return 269;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-12 The Background.mp3")) return 297;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-13 Motorcycle Drive By.mp3")) return 263;
    if (!strcmp(path, "Third Eye Blind/Third Eye Blind/01-14 God Of Wine.mp3")) return 318;
    return 0;
}
